# Site settings
title: Rubén Carabias Muñoz
description: 'Business Card Page'
#url: ''
baseurl: 'https://rubencarabias.github.io'
profilepic: '/images/1516978780859.jfif'
bkimage: '/images/cover.jpg'
google_analytics: G-WJN65C1ZFT
font_awesome: 'fd24312f53.js'

author:
  name: 'Rubén Carabias Muñoz'
  linkedin_username:  ruben-carabias-muñoz-79bba6bb
# github_username:  rubencarabias 
# meetup_name: Azure-Meetup-Rostock-MV
email: rubencarabias.primerob@gmail.com
#  twitter_username: rubencarabias
#  facebook_username: rubencarabias



# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
